menu:
  Home: { id: index, url: / }
  Archives: { id: archives, url: /archives }
  Tags: { id: tags, url: /tags }
  Categories: { id: categories, url: /categories }
  Github: { id: github, url: "https://github.com/galexrt" }
  Steam: { id: steam, url: "https://steamcommunity.com/id/galexrt" }

favicon: /images/favicon.png
avatar: /images/avatar.png

background-root: /images/background/
background: [ 1.jpg, 2.jpg, 3.jpg ]

rss: /atom.xml

## duoshuo short name. refer to http://dev.duoshuo.com/docs/501e6ce1cff715f71800000d
duoshuo_shortname:
disqus_shortname:

# google analytics id
google_analytics: UA-74383279-1
author_link: /about
privacy_policy:

gce_code:
