menu:
  Home: { id: index, url: / }
  Archives: { id: archives, url: /archives }
  Tags: { id: tags, url: /tags }
  Categories: { id: categories, url: /categories }
  Links: { id: links, url: /links }

github: galexrt

background-root: /images/background/
background: [ 1.jpg, 2.jpg, 3.jpg ]

avatar: /images/avatar.png

#### Comment
duoshuo:
  short_name: YOUR_DUOSHUO_SHORT_NAME    ## duoshuo short name. refer to http://dev.duoshuo.com/docs/501e6ce1cff715f71800000d

disqus_shortname:

# analytics ids
google_analytics: UA-74383279-1

rss: /atom.xml
